apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8085
    - name: debug
      protocol: TCP
      port: 5005
      targetPort: 5005
  type: NodePort
