version: '3.8'

services:
  postgres-basket:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: basketdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  postgres-product:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  postgres-order:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
