server:
  port: 8085

spring:
  application:
    name: frontend-service

logging:
  level:
    org.springframework.web.client: DEBUG

basket-service:
  url: http://basket-service:8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
