apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: SPRING_PROFILES_ACTIVE
            - name: EUREKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: EUREKA_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server-service
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
