apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # 'password' in base64
  EUREKA_PASSWORD: cGFzc3dvcmQ=    # 'password' in base64
