# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Environment variables to configure PostgreSQL
ENV POSTGRES_DB=mydatabase
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword

# Expose the default PostgreSQL port
EXPOSE 5432
