apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-basket-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-product-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-order-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-basket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-basket
  template:
    metadata:
      labels:
        app: postgres-basket
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          env:
            - name: POSTGRES_DB
              value: basketdb
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-basket-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-basket-storage
          persistentVolumeClaim:
            claimName: postgres-basket-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-basket-service
spec:
  selector:
    app: postgres-basket
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          env:
            - name: POSTGRES_DB
              value: productdb
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-product-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-product-storage
          persistentVolumeClaim:
            claimName: postgres-product-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product-service
spec:
  selector:
    app: postgres-product
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-order
  template:
    metadata:
      labels:
        app: postgres-order
    spec:
      containers:
        - name: postgres
          image: postgres:14-alpine
          env:
            - name: POSTGRES_DB
              value: orderdb
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-order-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-order-storage
          persistentVolumeClaim:
            claimName: postgres-order-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order-service
spec:
  selector:
    app: postgres-order
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
