apiVersion: apps/v1
kind: Deployment
metadata:
  name: basket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basket-service
  template:
    metadata:
      labels:
        app: basket-service
    spec:
      containers:
        - name: basket-service
          image: basket-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
            - containerPort: 5007
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: SPRING_PROFILES_ACTIVE
            - name: POSTGRES_BASKET_HOST
              value: postgres-basket-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://$(POSTGRES_BASKET_HOST):$(POSTGRES_PORT)/basketdb
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: application-secrets
                  key: POSTGRES_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: application-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          envFrom:
            - configMapRef:
                name: application-config
---
apiVersion: v1
kind: Service
metadata:
  name: basket-service
spec:
  selector:
    app: basket-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
