apiVersion: v1
kind: Service
metadata:
  name: basket-service
spec:
  selector:
    app: basket-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: debug
      port: 5006
      targetPort: 5006
      nodePort: 30506
  type: NodePort
